### ISSUE TITLE
Provide several examples combining NiaARM

### ISSUE THREAD

**Issue by firefly-cpp** [firefly-cpp/arm-preprocessing#13]
Since the arm-preprocessing library is also intended to fit well with the NiaARM, it would be essential to prepare several examples involving NiaARM.

**Comment by firefly-cpp** [comment]
@lahovniktadej, this is very important

**Comment by lahovniktadej** [comment]
Examples provided in 8a657df7ec813c8f42c5b25c6487f693cd1e1bac.
