### ISSUE TITLE
Implement feature selection methods

### ISSUE THREAD

**Issue by firefly-cpp** [firefly-cpp/arm-preprocessing#14]

**Comment by lahovniktadej** [comment]
Implemented, tested, and documented in:
- 1ca9dc8c6ae64a9d47c72c2d8b4dabfef83c412b
- 1e3df15a52a10eee3fb9e6cd29cbd140d4904e4c
- 55a899cdccc23628cef7de093ab2699bdf1ea46f
- d067ce1cd99b3548d11bfbc3a10e3e16e0b26ee3
