### ISSUE TITLE
Implementation of discretization methods

### ISSUE THREAD

**Issue by firefly-cpp** [firefly-cpp/arm-preprocessing#3]
See examples: https://www.blog.trainindata.com/data-discretization-in-machine-learning/

**Comment by lahovniktadej** [comment]
Implemented, tested, and documented in:
- 8b337358e1cd59b4c4192247f99d8335ea615dce
- 22e71a92e98c1d4fdd150072827904fb045a8c3f
- ffdc636b1d59e3a1528ca3c6e190d5bfb232028a
- 2f2a33ef63303ff05b1f754b0878092173954cf6
- e45ad0723a1c469a62f530c349c30564cda7bee9
- 7602b55d2a8c2b3f9701b4b7f7c3ed45602294aa
- 6afec691bf5761828fc8dc2b85b720fa4e59a8d3
- 7ddf16967748cd936d8c7eee40a96abd15d2b0d3
