### ISSUE TITLE
Implement data squashing (euclidean and cosine)

### ISSUE THREAD

**Issue by firefly-cpp** [firefly-cpp/arm-preprocessing#6]
[Reference paper](https://www.iztok.xyz/static/publications/300.pdf)

Methods already implemented in NiaARM [framework.](https://github.com/firefly-cpp/NiaARM/blob/main/niaarm/preprocessing.py)

**Comment by lahovniktadej** [comment]
Implemented, tested, and documented in:
- b76e2672e7b8cf24932263bc30c21683b389797f
- 16651295996142df0832385cbb0c152983c1d338
- 3146d8285b2ee122eb594bd960e58d233a88c528
- 9d471390043622195f27440f61a9f29c52dcadcc
