### ISSUE TITLE
Dealing with missing values in datasets

### ISSUE THREAD

**Issue by firefly-cpp** [firefly-cpp/arm-preprocessing#7]
Implement several strategies for dealing with missing data in datasets, e.g.

- drop columns with missing values,
- imputation.

**Comment by lahovniktadej** [comment]
Implemented, tested, and documented in:
- aa5f77c530c0b2251b9110ec2149a2f69c5cd1a9
- 783f635c19502a924a8f0ebe7a1fb350ec137082
- d5952e2cff0849e60c5e32942b5c4e0b94accaed
- 0c9546df8ba3ef6550b527f7e0607104e52b545d
